name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: 17.6.0
      - run: apt-get install python3 -y
      - uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - run: apt-get remove python3 -y