name: lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up NodeJS v17.6.0
        uses: actions/setup-node@v3
        with:
          node-version: 17.6.0

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install
      
      - name: Lint project
        run: yarn lint

      - name: Uninstall Yarn
        run: npm uninstall -g yarn
        